# Generated by Django 4.1.13 on 2024-02-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marriage', '0008_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageName', models.TextField()),
                ('Image', models.ImageField(upload_to='pics')),
                ('ImagePosition', models.TextField()),
            ],
        ),
    ]
